book/application.md
book/intro.md

I kept the application page in there for future events and also for search engines.

Application - Remove link to form and from homepage.

---

.binder/Dockerfile
.github/dependabot.yml
.github/workflows/binder-badge.yml
.github/workflows/test.yaml
README.md
book/preliminary/github.md

add github actions for PRs

---

.github/workflows/binder-badge.yml
book/_config.yml

add google analytics id

---

.github/workflows/binder-badge.yml
.github/workflows/deploy.yaml
.github/workflows/test.yaml
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
book/norms/CoC.md
book/tutorials/index.md

A number of website fixes, link to tutorial development guide, github recomended repository code of conduct also minor improvements to github actions

add code-of-conduct, update actions, tutorial links

---

.gitignore
book/team.md
docker-compose.yml

See also https://github.com/uwhackweek/jupyterbook-template/issues/3

refactor team page

---

book/team.md

Trying to link to a non-github photo, so hopefully it works!

add myself (melissa) to team list

---

.github/workflows/qaqc.yaml
.github/workflows/test.yaml
book/tutorials/sar/sentinel1.ipynb

moves external link checking to separate workflow since network connections often fail, and we don't want that to prevent merging pull requests: https://github.com/snowex-hackweek/website/pull/33#issuecomment-850121853

separate qaqc from build CI, fix typos

---

book/_toc.yml
book/team.md
book/tutorials/core-datasets/core-datasets-tutorial.ipynb

The directions worked well to add a tutorial. Now I need to go back and put some real meat in the tutorial.

megan added a draft tutorial for the core-dataset tutorial

---

book/team.md

added the SWESARR tutorial contributors to the website's team markdown file.

dylan added SWESARR team members

---

book/preliminary/swc.md

updates to schedule for Tuesday, and some other page layout changes

swc page updates

---

.github/workflows/deploy.yaml
.github/workflows/netlifypreview.yaml
.github/workflows/qaqc.yaml
.github/workflows/test.yaml
book/preliminary/earthdata.md

fixes #70 
this uses a 'machine' nasa urs account created for the hackweek rather than anybody's personal userid and password

add netrc with nasa creds for book

---

book/_config.yml
book/tutorials/sar/sentinel1.ipynb

add html_image myst extension

---

.github/workflows/deploy.yaml
.github/workflows/netlifypreview.yaml
.github/workflows/test.yaml

Pass AWS_REGION environment variable to docker jb build 

---

book/tutorials/sar/uavsar-download.ipynb
book/tutorials/sar/uavsar.ipynb

The ASF download can be slow and error prone, so I've staged the converted Tifs in S3, and separated the original notebook into two. 1 focused on download and format conversion and the 2nd focused on plotting and analysis. Only the 2nd is rendered on the website, but both are accessible if you'd like to go over them during the tutorial. cc @jacktarricone @hpmarshall

Split UAVSAR into two notebooks 

---

book/schedule.md

This PR is a proposed change to the schedule on day 1. If people are ok with it we can merge into the main schedule.

shift schedule forward on day 1

---

book/tutorials/lis/1_exploring_lis_output.ipynb

This PR adds the SNODAS and SNOTEL comparison sections and makes minor edits throughout the main LIS tutorial notebook.

LIS tutorial: edits + add SNODAS and SNOTEL comparison sections

---

book/_toc.yml
book/tutorials/core-datasets/index.md
book/tutorials/database/index.md
book/tutorials/day_1.md
book/tutorials/day_2.md
book/tutorials/day_3.md
book/tutorials/day_4.md
book/tutorials/gpr/gpr.ipynb
book/tutorials/index.md
book/tutorials/lidar/ICESat2_tutorial.ipynb
book/tutorials/microstructure/microstructure-tutorial.ipynb
book/tutorials/sar/index.md

My stab at grouping the tutorials by days.
Also added table of contents for each day and section.

TOC - Group tutorials by days

---

.github/workflows/deploy.yaml
.github/workflows/netlifypreview.yaml
.github/workflows/test.yaml

follow up to #102 with a path fix

fix path in github actions to build script

---

.github/workflows/deploy.yaml
.github/workflows/netlifypreview.yaml
.github/workflows/qaqc.yaml
.github/workflows/test.yaml

had a typo in earthdata login environment variable. this attempts to use a github actions cache for the book/_build directory

fix earthdata login, try cache

---

.github/workflows/deploy.yaml
.github/workflows/netlifypreview.yaml
.github/workflows/qaqc.yaml
.github/workflows/test.yaml

fixes for github actions workflows

---

book/_config.yml

Mainly trying to trigger a new deploy that re-renders the book. The previous deploy had a AWS timeout when accessing the SnowEx S3 bucket

Config - Remove empty line

---

book/schedule.md

Adding in two structured virtual happy hour/coffee breaks that Charley will facilitate

Schedule breaks

---

book/_config.yml
book/references.bib
book/tutorials/microstructure/microstructure-tutorial.ipynb

added a few edits that put the SMP comparison in context, and provide a better jumping off point for a microstructure-related project.

edits for new SMP relationship

---

book/schedule.md

proposed layout of Day 2 to accommodate missed GitHub content

updated schedule for Day 2

---

book/tutorials/sar/swesarr.ipynb

Trying again with a new branch! Really gotta up my git game one of these days ❌

Updated SWESARR

---

book/_toc.yml
book/schedule.md
book/tutorials/day_5.md
book/tutorials/open_science.md
book/tutorials/open_source_software.md

Videos for Day 4 are also part of this

Friday - Open Scienc/Source

---

.github/workflows/cron.yaml
.github/workflows/deploy.yaml
.github/workflows/manual.yaml
.github/workflows/netlifypreview.yaml
.github/workflows/qaqc.yaml
.github/workflows/test.yaml
book/_config.yml
book/_toc.yml
book/tutorials/geospatial/index.md
book/tutorials/lidar/ASO_data_tutorial.ipynb
book/tutorials/nsidc-access/nsidc-data-access.ipynb
book/tutorials/sar/swesarr.ipynb
book/tutorials/sar/uavsar-download.ipynb
book/tutorials/thermal-ir/index.md

Improvements to CI, ensure all notebooks render

---

book/tutorials/camera-traps-tutorial/timelapse-camera-tutorial.ipynb
book/tutorials/core-datasets/03_practice-querying.ipynb
book/tutorials/database/1_getting_started_example.ipynb
book/tutorials/database/2_database_structure.ipynb
book/tutorials/database/3_forming_queries.ipynb
book/tutorials/database/4_get_spiral_example.ipynb
book/tutorials/database/5_plot_raster_example.ipynb
book/tutorials/database/6_exporting_data.ipynb
book/tutorials/geospatial/SNOTEL_query.ipynb
book/tutorials/gpr/gpr.ipynb
book/tutorials/machine-learning/Machine_Learning_Tutorial.ipynb
book/tutorials/microstructure/microstructure-tutorial.ipynb
book/tutorials/thermal-ir/thermal-ir-tutorial.ipynb

Per our convo in #15 we have pointed the url `db.snowexdata.org` to the current IP address of the DB from hackweek.

Migrated the notebooks to point to new URL 

---

book/tutorials/geospatial/SNOTEL_query.ipynb

Looks like they migrated to secure http some time around August 25, 2021

Update url for CUAHSI WOF endpoint in SNOTEL_query

---

book/_toc.yml
book/intro.md
book/tutorials/day_1.md
book/tutorials/day_2.md
book/tutorials/day_3.md
book/tutorials/day_4.md
book/tutorials/day_5.md
book/tutorials/index.md
book/tutorials/lidar/index.md

Fixes https://github.com/snowex-hackweek/website/issues/149

remove tutorial organization by day, add summary table
